<?php

namespace Database\Seeders;

use App\Models\Section;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SectionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data Source = https://openeducationalberta.ca/medicalterminology/chapter/9-5-hospital-units-and-departments/
     * Also, https://www.disabled-world.com/definitions/hospital-departments.php
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('sections')->truncate();
        DB::table('section_translations')->truncate();

        $sections = [
            [
                'en' => [
                    'name' => 'Burn Unit',
                    'description' => 'This unit provides care to patients who have suffered advanced and complicated burn injuries (Washington State Department of Health, 2022). These patients have complex and intensive care requirements because a number of complications, including infections, are common when a patient has severe burns.'
                ],
                'ar' => [
                    'name' => 'وحدة الحروق',
                    'description' => 'تقدم هذه الوحدة الرعاية للمرضى الذين تعرضوا لإصابات حروق متقدمة ومعقدة (وزارة الصحة في واشنطن، 2022). يتطلب علاج هؤلاء المرضى رعاية معقدة ومكثفة بسبب تعدد المضاعفات التي تحدث عادة عندما يكون للمريض حروق شديدة.'
                ]
            ],
            [
                'en' => [
                    'name' => 'Cardiology Unit',
                    'description' => 'This unit focuses on care for patients whose main reason for admission is cardiac-related. It would not, ideally, care for a patient in the acute phase of a myocardial infarction but would handle the aftercare once the patient was somewhat stabilized. The unit would also have patients with congestive heart failure, unstable blood pressure, and other cardiac pathologies.'
                ],
                'ar' => [
                    'name' => 'وحدة أمراض القلب',
                    'description' => 'تتركز هذه الوحدة على رعاية المرضى الذين تكون السبب الرئيسي لدخولهم هو مشاكل القلب. عادةً ما لن تعتني بمريض في مرحلة حادة من نوبة قلبية، ولكنها ستتولى الرعاية بعد استقرار حالة المريض إلى حد ما. وسيكون هناك أيضًا مرضى يعانون من قصور القلب التنفسي، وضغط الدم غير المستقر، وأمراض أخرى متعلقة بالقلب.'
                ]
            ],
            [
                'en' => [
                    'name' => 'Coronary Care Unit (CCU)',
                    'description' => 'This specialized intensive care unit provides care for patients with more complex and unstable cardiac issues. Acute cardiac events such as a myocardial infarction or even open heart surgery would be reasons for admission to this unit (Washington State Department of Health, 2022).'
                ],
                'ar' => [
                    'name' => 'وحدة رعاية القلب التاجي (CCU)',
                    'description' => 'هذه الوحدة المتخصصة في الرعاية المكثفة تقدم الرعاية للمرضى الذين يعانون من مشاكل قلبية معقدة وغير مستقرة. يُعَدُّ حدوث أحداث قلبية حادة مثل نوبة قلبية أو حتى جراحة القلب المفتوح أسبابًا لدخول هذه الوحدة (وزارة الصحة في واشنطن، 2022).'
                ]
            ],
            ['en' => ['name' => 'Day Surgery Unit', 'description' => 'Patients come to this unit if they are to undergo less-complicated surgeries that do not require an overnight hospital stay. Often patients arrive in the morning and then leave once the procedure is complete and their condition is stable (Whitlock, 2020).'], 'ar' => ['name' => 'وحدة الجراحة اليومية', 'description' => 'يأتي المرضى إلى هذه الوحدة إذا كانوا يعتزمون الخضوع لجراحات أقل تعقيدًا لا تتطلب بقاء في المستشفى ليلة. غالبًا ما يصل المرضى في الصباح ويغادرون بمجرد اكتمال الإجراء وتحسُّن حالتهم (ويتلوك، 2020).']],
            ['en' => ['name' => 'Dialysis (Renal) Unit', 'description' => 'Patients on this unit often come in for dialysis, as can be seen in Fig. 9.15, and then leave once the procedure is complete. Often the same patients come in weekly or a few times a week for dialysis. These patients have some level of kidney failure or other pathology, and their kidneys can no longer filter their blood. Some units are designed so the patients stay on the unit because their condition will not allow them to go home between treatments.'], 'ar' => ['name' => 'وحدة الغسيل (الكلوي)', 'description' => 'غالبًا ما يأتي المرضى في هذه الوحدة للغسيل، كما هو موضح في الشكل 9.15، ثم يغادرون بمجرد الانتهاء من الإجراء. غالبًا ما يأتي نفس المرضى أسبوعيًا أو عدة مرات في الأسبوع للغسيل. يعاني هؤلاء المرضى من مستوى منخفض من فشل الكلي أو أمراض أخرى، ولا تستطيع كليتاهم تنقية دمهم بشكل صحيح. وتم تصميم بعض الوحدات بحيث يبقى المرضى على الوحدة لأن حالتهم لا تسمح لهم بالعودة إلى المنزل بين العلاجات.']],
            ['en' => ['name' => 'Emergency Room (ER)', 'description' => ' Patients typically access the ER if they need emergency care. The medical professionals on this unit treat a vast array of urgent and acute injuries and pathologies. For example, a patient may have had a motor vehicle accident or a myocardial infarction and requires immediate care.'], 'ar' => ['name' => 'وحدة الطوارئ (الطوارئ)', 'description' => ' يقوم المرضى عادة بزيارة وحدة الطوارئ إذا كانوا بحاجة إلى رعاية طارئة. يقدم المهنيون الطبيون في هذه الوحدة رعاية متنوعة للإصابات العاجلة والحادة والأمراض. على سبيل المثال، قد يكون المريض قد تعرض لحادث مروري أو نوبة قلبية ويحتاج إلى رعاية فورية.']],
            ['en' => ['name' => 'Gastroenterology Unit', 'description' => ' Patients are admitted to this unit if they have a pathology that affects their stomach or intestines. Common conditions could be exacerbations (worsening of symptoms) of Crohn’s disease or ulcerative colitis.'], 'ar' => ['name' => 'وحدة الجهاز الهضمي', 'description' => ' يتم قبول المرضى في هذه الوحدة إذا كانوا يعانون من أمراض تؤثر على المعدة أو الأمعاء. قد تكون الحالات الشائعة تفاقمات لأمراض كرون أو التهاب القولون التقرحي.']],
            ['en' => ['name' => 'Gynecology Unit', 'description' => ' This unit focuses on treating ailments of the female reproductive system. Patients could be experiencing fibroid tumours, exacerbations of endometriosis, uterine bleeding, or other disorders. However, patients would not go to this unit for pregnancy-related issues.'], 'ar' => ['name' => 'وحدة النساء والتوليد', 'description' => ' تركز هذه الوحدة على علاج أمراض الجهاز التناسلي الأنثوي. قد يعاني المرضى من أورام الليفية، أو تفاقم لمرض الاندوميتريوز، أو نزيف الرحم، أو اضطرابات أخرى. ومع ذلك، فإن المرضى لن يتوجهوا إلى هذه الوحدة بسبب مشاكل متعلقة بالحمل.']],
            ['en' => ['name' => 'Geriatric Unit', 'description' => ' Patients on this unit can be admitted for various reasons, but the main thing they have in common is age. Geriatric patients are generally over the age of 75, though that may vary depending on the policy and specific cutoff age for geriatric status in the local area.'], 'ar' => ['name' => 'وحدة المسنين', 'description' => ' يمكن قبول المرضى في هذه الوحدة لأسباب مختلفة، ولكن الشيء الرئيسي الذي يجمعهم هو العمر. يكون المرضى في وحدة المسنين عادة فوق سن 75، على الرغم من أن ذلك قد يختلف اعتمادًا على السياسة والعمر الحد الأدنى المحدد للحالة المسنة في المنطقة المحلية.']],
            ['en' => ['name' => 'Intensive Care Unit (ICU)', 'description' => ' In this unit, seriously ill patients receive intense and specialized care such as monitoring and advanced life support (Washington State Department of Health, 2022). The patients are often intubated and have machines breathing for them, as shown in Fig. 9.16. They also receive one-on-one nursing care (Washington State Department of Health, 2022).'], 'ar' => ['name' => 'وحدة العناية المكثفة (ICU)', 'description' => ' في هذه الوحدة، يتلقى المرضى الذين يعانون من حالات خطيرة رعاية مكثفة ومتخصصة مثل المراقبة والدعم الحيوي المتقدم (وزارة الصحة في واشنطن، 2022). عادةً ما يتم تجهيز المرضى بأنابيب التنفس ويتم التنفس عنهم باستخدام الأجهزة، كما هو موضح في الشكل 9.16. كما يحصلون على رعاية تمريض فردية (وزارة الصحة في واشنطن، 2022).']],
            ['en' => ['name' => 'Labour and Delivery (L&D) Unit', 'description' => ' Patients only come to this unit if they are in labour or at risk for immediate labour. Patients would not come to this unit if they were early on in their pregnancy or for fertility issues. Once the patient has delivered the baby, the mother and infant stay on the unit until stable, but they are often discharged within a day or two at the most.'], 'ar' => ['name' => 'وحدة الولادة والتوصيل (L&D)', 'description' => ' يأتي المرضى إلى هذه الوحدة فقط إذا كانوا في مرحلة الولادة أو في خطر الولادة الفوري. لن يتوجه المرضى إلى هذه الوحدة إذا كانوا في مراحل مبكرة من الحمل أو بسبب مشاكل الخصوبة. بمجرد ولادة الطفل، يظل الأم والطفل على الوحدة حتى تستقر حالتهما، ولكن غالبًا ما يتم إخراجهما من المستشفى في يوم أو يومين على الأكثر.']],
            ['en' => ['name' => 'Medicine Unit', 'description' => ' This unit provides care for a vast array of illnesses. Patients would not be treated for conditions that require more complex care, but they often have pathologies such as pneumonia, bronchitis, or mobility issues, or they are waiting for placement in another facility, such as long-term care. Often a patient’s condition does not warrant being on a more specialized unit, but rather the patient may have a number of comorbidities (more than one condition or disease at the same time).'], 'ar' => ['name' => 'وحدة الطب', 'description' => ' تقدم هذه الوحدة الرعاية لمجموعة واسعة من الأمراض. لن يتم علاج المرضى للحالات التي تتطلب رعاية أكثر تعقيدًا، لكنهم غالبًا ما يعانون من أمراض مثل الالتهاب الرئوي، والتهاب الشعب الهوائية، أو مشاكل في الحركة، أو ينتظرون نقلهم إلى مرفق آخر، مثل الرعاية طويلة الأمد. غالبًا ما لا تستدعي حالة المريض أن يكون على وحدة أخصائية أكثر، بل قد تكون لديه عدة أمراض مصاحبة (أكثر من حالة أو مرض في نفس الوقت).']],
            ['en' => ['name' => 'Nephrology Unit', 'description' => ' Patients on this unit have a pathology that affects the kidneys. They may require dialysis, which is often done in a dialysis unit (see above), but they may have other pathologies such as kidneys stones, blockages, or other issues with kidney function.'], 'ar' => ['name' => 'وحدة الكلية', 'description' => ' يعاني المرضى على هذه الوحدة من أمراض تؤثر على الكليتين. قد يحتاجون إلى الغسيل، الذي يتم عادةً في وحدة الغسيل (انظر أعلاه)، ولكن قد يكون لديهم مشاكل أخرى مثل حصى الكلى، أو انسدادات، أو مشاكل أخرى تتعلق بوظيفة الكلى.']],
            ['en' => ['name' => 'Neurology Unit', 'description' => ' There are a number of conditions that can affect the nervous system, and those would be prevalent in patients on this unit. For example, a patient may have had a stroke that was treated in the acute phase but now requires aftercare. Other conditions treated on this unit include head trauma, epilepsy, neuromuscular disorders, or tumours.'], 'ar' => ['name' => 'وحدة الأعصاب', 'description' => ' هناك عدد من الحالات التي يمكن أن تؤثر على الجهاز العصبي، وسيكون المرضى المصابين بهذه الحالات شائعين في هذه الوحدة. على سبيل المثال، قد يكون المريض قد تعرض لجلطة دماغية تم علاجها في المرحلة الحادة ولكنه يحتاج الآن إلى رعاية متابعة. ومن بين الحالات الأخرى المعالجة في هذه الوحدة:  الإصابة الرأسية، والصرع، واضطرابات العضلات والأعصاب، أو الأورام.']],
            ['en' => ['name' => 'Neonatal Intensive Care Unit (NICU)', 'description' => ' This unit is similar to the ICU (see above) but provides advanced care for newborn infants who require monitoring and advanced life support (Washington State Department of Health, 2022). One type of NICU can be seen in Fig. 9.17.'], 'ar' => ['name' => 'وحدة الرعاية المكثفة للمواليد الجدد (NICU)', 'description' => ' هذه الوحدة مشابهة لوحدة العناية المكثفة (انظر أعلاه) وتقدم رعاية متقدمة للأطفال الرضع الذين يحتاجون إلى المراقبة والدعم الحيوي (وزارة الصحة في واشنطن، 2022). يمكن رؤية نوع واحد من وحدة NICU في الشكل 9.17.']],
            ['en' => ['name' => 'Oncology Unit', 'description' => ' Patients on this unit have been diagnosed with some form of cancer.'], 'ar' => ['name' => 'وحدة الأورام', 'description' => ' يتم قبول المرضى في هذه الوحدة إذا تم تشخيصهم بأي نوع من أنواع السرطان.']],
            ['en' => ['name' => 'Operating Room (OR)', 'description' => ' This is where surgeries for both in-patients and outpatients are performed; an example of surgery taking place in an operating room is shown in Fig. 9.18 (Whitlock, 2020). If the patient is to remain in the hospital, they will be moved to the recovery room (see below), then to the surgery unit for post-operative care.'], 'ar' => ['name' => 'غرفة العمليات (OR)', 'description' => ' هذا هو المكان الذي يتم فيه إجراء الجراحات للمرضى المنومين والمرضى الخارجيين؛ ويُظهر مثال لجراحة تجرى في غرفة العمليات في الشكل 9.18 (ويتلوك، 2020). إذا كان المريض سيبقى في المستشفى، فسيتم نقله إلى غرفة الاستراحة (انظر أدناه)، ثم إلى وحدة الجراحة للعناية ما بعد العملية.']],
            ['en' => ['name' => 'Outpatient Department (OPD)', 'description' => ' This unit treats patients who do not need to stay in the hospital overnight. They have complex needs but can return home in the evening. Patients come to the hospital for some form of treatment, such as rehabilitation, mental health care, or medication, then leave the OPD afterwards (Whitlock, 2020).'], 'ar' => ['name' => 'قسم العيادات الخارجية (OPD)', 'description' => ' تعالج هذه الوحدة المرضى الذين لا يحتاجون إلى البقاء في المستشفى ليلاً. لديهم احتياجات معقدة ولكنهم يمكنهم العودة إلى منازلهم في المساء. يأتي المرضى إلى المستشفى للحصول على أشكال مختلفة من العلاج، مثل التأهيل، أو الرعاية الصحية النفسية، أو العلاج بالأدوية، ثم يغادرون قسم العيادات الخارجية بعدها (ويتلوك، 2020).']],
            ['en' => ['name' => 'Orthopedic Unit', 'description' => ' Patients admitted to this unit have issues with their bones or joints. In many cases, they have had an injury and require substantial aftercare and rehabilitation. Patients may also have a chronic anomaly to their bones that requires intervention and treatment.'], 'ar' => ['name' => 'وحدة الجراحة العظمية', 'description' => ' يتم قبول المرضى في هذه الوحدة لديهم مشاكل في العظام أو المفاصل. في كثير من الحالات، قد تكون هناك إصابة ويحتاجون إلى رعاية متابعة وتأهيل كبير. قد يكون لدى المرضى أيضًا تشوه مزمن في العظام يتطلب التدخل والعلاج.']],
            ['en' => ['name' => 'Palliative Care Unit', 'description' => ' This unit provides care for patients at the end of life (Whitlock, 2020). When there are no other treatment options for patients and their health condition is terminal, they can come to this unit, where the focus of care is on patient comfort (Whitlock, 2020).'], 'ar' => ['name' => 'وحدة الرعاية التوقيفية', 'description' => ' تقدم هذه الوحدة الرعاية للمرضى في نهاية حياتهم (ويتلوك، 2020). عندما لا توجد خيارات علاجية أخرى للمرضى وتكون حالتهم الصحية غير قابلة للشفاء، يمكنهم الذهاب إلى هذه الوحدة، حيث يكون التركيز على راحة المريض (ويتلوك، 2020).']],
            ['en' => ['name' => 'Pre-admission Clinic (PAC)', 'description' => ' This area of the hospital is where patients go before surgery and before they are admitted to the hospital, so they can prepare and be educated about the procedure they will be having. The healthcare professionals on this unit ensure that patients are prepared and in the condition needed for surgery to be performed.'], 'ar' => ['name' => 'عيادة التحضير قبل الدخول (PAC)', 'description' => ' هذا المكان في المستشفى هو المكان الذي يذهب إليه المرضى قبل الجراحة وقبل أن يتم قبولهم في المستشفى، حتى يتمكنوا من التحضير والتعلم حول الإجراء الذي سيخضعون له. يضمن المهنيون الصحيون على هذه الوحدة أن المرضى مستعدون وفي الحالة المطلوبة لإجراء الجراحة.']],
            ['en' => ['name' => 'Pediatric Unit', 'description' => ' This unit may be a general pediatric unit or a specialized one for certain conditions such as trauma or pulmonary conditions, but the focus is on providing care to patients under the age of 18 (Washington State Department of Health, 2022).'], 'ar' => ['name' => 'وحدة الأطفال', 'description' => ' يمكن أن تكون هذه الوحدة وحدة عامة لطب الأطفال أو وحدة متخصصة لبعض الحالات مثل الإصابات أو حالات الجهاز التنفسي، ولكن التركيز هو تقديم الرعاية للمرضى الذين تقل أعمارهم عن 18 عامًا (وزارة الصحة في واشنطن، 2022).']],
            ['en' => ['name' => 'Pediatric Intensive Care Unit (PICU)', 'description' => ' This unit is similar to the ICU (see above), but the advanced care provided is for pediatric patients—children under the age of 18—who require intensive care and advanced life support (Washington State Department of Health, 2022).'], 'ar' => ['name' => 'وحدة الرعاية المكثفة للأطفال (PICU)', 'description' => ' هذه الوحدة مشابهة لوحدة العناية المكثفة (انظر أعلاه)، ولكن الرعاية المتقدمة المقدمة هي للمرضى الأطفال - الأطفال دون سن 18 عامًا - الذين يحتاجون إلى الرعاية المكثفة والدعم الحيوي (وزارة الصحة في واشنطن، 2022).']],
            ['en' => ['name' => 'Postpartum Unit', 'description' => ' This unit admits women who have been on the L&D unit and have given birth. In some cases, either the mother or infant require more long-term care, so they are transferred to the postpartum unit. The infant could have issues with jaundice, feeding, or elimination (bowel or bladder issues), or the mother may have had a complicated cesarean section or difficult delivery.'], 'ar' => ['name' => 'وحدة ما بعد الولادة', 'description' => ' تقبل هذه الوحدة النساء اللاتي كانوا في وحدة الولادة وقد أنجبن. في بعض الحالات، قد يحتاج إما الأم أو الرضيع إلى رعاية طويلة الأمد، لذلك يتم نقلهم إلى وحدة ما بعد الولادة. قد يكون لدى الرضيع مشاكل مع ارتفاع نسبة الصفراء في الدم، أو مشاكل في التغذية، أو مشاكل في الإخراج (أمور تتعلق بالأمعاء أو المثانة)، أو قد يكونت للأم جراحة قيصرية معقدة أو ولادة صعبة.']],
            ['en' => ['name' => 'Psychiatry/Mental Health Unit', 'description' => ' There are various kinds of mental health units in a hospital. Some have locked units where patients are under constant observation, others have patients who stay on the unit all the time, and still others allow patients to leave during the day and return in the evening. However, all the patients on this type of unit have some form of mental health diagnosis and are receiving care for that condition.'], 'ar' => ['name' => 'وحدة الطب النفسي / الصحة النفسية', 'description' => ' هناك أنواع مختلفة من وحدات الصحة النفسية في المستشفى. تحتوي بعضها على وحدات مغلقة حيث يتم مراقبة المرضى باستمرار، والبعض الآخر يتواجد به مرضى يبقون على الوحدة طوال الوقت، ويُسمح للبعض الآخر بالخروج خلال النهار والعودة في المساء. ومع ذلك، فإن جميع المرضى في هذا النوع من الوحدة لديهم نوع ما من تشخيص الصحة النفسية ويتلقون الرعاية لهذه الحالة.']],
            ['en' => ['name' => 'Pulmonary Unit', 'description' => ' Patients on this unit have some form of acute or chronic pulmonary condition; for example, injuries to the lungs such as atelectasis or pleural effusion. They might also have chronic conditions such as uncontrolled asthma, bronchitis, COPD, or inflammation or infection in the respiratory system.'], 'ar' => ['name' => 'وحدة الجهاز التنفسي', 'description' => ' يعاني المرضى على هذه الوحدة من بعض أشكال الحالات التنفسية الحادة أو المزمنة؛ على سبيل المثال، الإصابات في الرئتين مثل الانطباع الرئوي أو انسداد المستدق. قد يكون لديهم أيضًا حالات مزمنة مثل الربو غير المسيطر عليه، والتهاب الشعب الهوائية، متلازمة فشل التنفس المزمن، أو التهاب أو عدوى في الجهاز التنفسي.']],
            ['en' => ['name' => 'Recovery Room (RR)', 'description' => ' Patients are taken to this unit after surgery to wait for the anesthesia to wear off; an example of a recovery room can be seen in Fig. 9.19 (Whitlock, 2020). Patients remain in the recovery room until they are able to breathe on their own and respond appropriately to healthcare providers. Once stable, they will either return to the day surgery unit if they are to be discharged that day or they go back to the surgery unit they were admitted to.'], 'ar' => ['name' => 'غرفة الاستراحة (RR)', 'description' => ' يتم نقل المرضى إلى هذه الوحدة بعد الجراحة للانتظار حتى يتلاشى تأثير التخدير؛ ويمكن رؤية مثال لغرفة الاستراحة في الشكل 9.19 (ويتلوك، 2020). يبقى المرضى في غرفة الاستراحة حتى يتمكنوا من التنفس بأنفسهم والاستجابة بشكل مناسب لمقدمي الرعاية الصحية. بمجرد استقرارهم، سيعودون إما إلى وحدة جراحة النهار إذا كانوا سيغادرون في ذلك اليوم أو يعودون إلى وحدة الجراحة التي تم قبولهم فيها.']],
            ['en' => ['name' => 'Rehabilitation', 'description' => ' This area may be in the hospital or is a separate facility, but patients go to rehabilitation to increase their strength and improve their functioning so they can go home (Washington State Department of Health, 2022). After an injury or surgery, patients who requires more time and rehabilitation before they can return home are admitted to a rehabilitation unit or facility.'], 'ar' => ['name' => 'التأهيل', 'description' => ' قد تكون هذه المنطقة في المستشفى أو مرفق منفصل، ولكن المرضى يتوجهون إلى التأهيل لزيادة قوتهم وتحسين وظائفهم حتى يتمكنوا من العودة إلى منازلهم (وزارة الصحة في واشنطن، 2022). بعد الإصابة أو الجراحة، يتم قبول المرضى الذين يحتاجون إلى المزيد من الوقت والعلاج التأهيلي قبل أن يتمكنوا من العودة إلى منازلهم في وحدة أو مرفق للتأهيل.']],
            ['en' => ['name' => 'Specialty Clinics', 'description' => ' Depending on the hospital, these clinics can be numerous and vary greatly. There can be diabetes clinics, kidney clinics, blood pressure clinics, and intravenous therapy clinics. There may be other clinics as well, and the number and types of specialty clinics will depend on the size of the hospital and the population they provide care for (Ernstmeyer & Christman, 2021).'], 'ar' => ['name' => 'عيادات التخصصات', 'description' => ' يمكن أن تكون هذه العيادات متعددة ومتنوعة تبعًا للمستشفى. قد تكون هناك عيادات للسكري، وعيادات الكلى، وعيادات ضغط الدم، وعيادات العلاج الوريدي. قد تكون هناك أيضًا عيادات أخرى، وسيعتمد عدد وأنواع عيادات التخصصات على حجم المستشفى والسكان الذين يتلقون الرعاية (إيرنستماير وكريستمان، 2021).']],
            ['en' => ['name' => 'Surgery Units', 'description' => ' There are many specialty surgery units in a hospital; for example, a thoracic unit that focuses on chest surgeries, or units that focus on neurological or gynecological surgeries. These units will have patients who have had surgeries that relate to the specialty area. There are also general surgery units that will have patients who have had a variety of procedures; however, those procedures will not be specialized or require complex care. Instead, patients on those units will have had routine procedures such as an appendectomy. It is important to note that patients on these units are admitted because they either require surgery or have just had surgery. Also, surgery does not actually occur on these units—the patients leave the unit to go to the OR, as discussed above, then return to the surgery unit for post-op care.'], 'ar' => ['name' => 'وحدات الجراحة', 'description' => ' هناك العديد من وحدات الجراحة المتخصصة في المستشفى؛ على سبيل المثال، وحدة الجراحة الصدرية التي تركز على الجراحات الصدرية، أو الوحدات التي تركز على الجراحات العصبية أو النسائية. ستحتوي هذه الوحدات على مرضى أجروا جراحات ذات صلة بمجال التخصص. هناك أيضًا وحدات الجراحة العامة التي ستحتوي على مرضى أجروا مجموعة متنوعة من الإجراءات؛ ومع ذلك، فإن تلك الإجراءات لن تكون متخصصة أو تتطلب رعاية معقدة. بدلاً من ذلك، سيكون لدى المرضى في هذه الوحدات إجراءات روتينية مثل استئصال الزائدة الدودية. من المهم أن نلاحظ أن المرضى في هذه الوحدات يتم قبولهم لأنهم إما بحاجة لجراحة أو لأنهم أجروا جراحة للتو. أيضًا، لا يتم إجراء الجراحة فعليًا في هذه الوحدات - يغادر المرضى الوحدة للذهاب إلى غرفة العمليات، كما تم ذكره أعلاه، ثم يعودون إلى وحدة الجراحة للرعاية ما بعد العملية.']],
            ['en' => ['name' => 'Urology Unit', 'description' => ' Patients are admitted to this unit because they have a pathology or anomaly that relates to the urinary system and/or male genitourinary system. Conditions, disorders, and diseases such as prostate disease and renal and bladder dysfunctions may require a patient to be admitted to this unit depending on the severity of the patient’s condition.'], 'ar' => ['name' => 'وحدة الجراحة البولية', 'description' => ' يتم قبول المرضى في هذه الوحدة لديهم مرض أو تشوه يتعلق بالجهاز البولي و / أو الجهاز التناسلي للذكور. قد تتطلب حالات واضطرابات وأمراض مثل الأمراض البروستاتية واضطرابات الكلى والمثانة من المريض الدخول إلى هذه الوحدة اعتمادًا على شدة حالته.']],
        ];

        foreach ($sections as $section) {
            Section::create($section);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
